version: '3'
services:

  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: master2
    ports:
      - 3306:3306
  pma: 
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8889:80
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb